version: "3"

services:
  wikiless:
    container_name: wikiless
    build: wiki/
    image: local/wikiless
    networks:
      - wikiless
      - nginx
    environment:
      REDIS_HOST: redis://wikiless_redis:6379
    # ports:
    #   - "8180:8080"
    depends_on:
      - wikiless_redis
    restart: unless-stopped

  wikiless_redis:
    container_name: wikiless_redis
    image: "redis:alpine"
    networks:
      - wikiless
    ports:
      - "6379"
    restart: unless-stopped

networks:
  nginx:
    external: true
  wikiless:
